# Generated by Django 4.2.7 on 2025-12-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape_MakaziListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('link', models.URLField(unique=True)),
                ('price', models.CharField(max_length=100)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_image_url', models.URLField(blank=True, null=True)),
                ('posted_on_fb', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
                ('property_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('bedrooms', models.IntegerField(blank=True, db_index=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('area_sqft', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['title', 'location', 'description'], name='makazi_scra_title_9ebb39_idx'), models.Index(fields=['property_type'], name='makazi_scra_propert_c4332c_idx'), models.Index(fields=['bedrooms'], name='makazi_scra_bedroom_b73a66_idx'), models.Index(fields=['price'], name='makazi_scra_price_212fc2_idx'), models.Index(fields=['is_featured'], name='makazi_scra_is_feat_e75d47_idx'), models.Index(fields=['scraped_at'], name='makazi_scra_scraped_a5fe3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='makazi.scrape_makazilisting')),
            ],
        ),
    ]
