# Generated by Django 4.2.7 on 2025-12-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makazi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape_makazilisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scrape_makazilisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
