# Generated by Django 4.2.7 on 2025-12-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makazi', '0002_scrape_makazilisting_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scrape_makazilisting',
            name='makazi_scra_title_9ebb39_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrape_makazilisting',
            name='makazi_scra_price_212fc2_idx',
        ),
        migrations.AddField(
            model_name='scrape_makazilisting',
            name='digits_price',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='scrape_makazilisting',
            index=models.Index(fields=['title', 'location'], name='makazi_scra_title_30345a_idx'),
        ),
        migrations.AddIndex(
            model_name='scrape_makazilisting',
            index=models.Index(fields=['is_verified'], name='makazi_scra_is_veri_94c496_idx'),
        ),
    ]
