# Generated by Django 4.2.7 on 2025-12-23 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makazi', '0003_remove_scrape_makazilisting_makazi_scra_title_9ebb39_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField()),
                ('apartment_type', models.CharField(choices=[('studio', 'Studio'), ('1bed', '1 Bedroom'), ('2bed', '2 Bedrooms'), ('3bed', '3 Bedrooms'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex')], max_length=50)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_rooms', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('area_sqft', models.IntegerField()),
                ('floor_number', models.IntegerField(default=1)),
                ('total_floors', models.IntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='apartments/main/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='apartments/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='apartments/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='apartments/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='apartments/')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='makazi.apartment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('duration_months', models.IntegerField(default=1)),
                ('number_of_guests', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='makazi.apartment')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['location'], name='makazi_apar_locatio_4130e6_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['price_per_month'], name='makazi_apar_price_p_fa5943_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['is_available'], name='makazi_apar_is_avai_d246ee_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['is_featured'], name='makazi_apar_is_feat_8310c0_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['created_at'], name='makazi_apar_created_f17d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentreview',
            index=models.Index(fields=['apartment'], name='makazi_apar_apartme_6b4f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentreview',
            index=models.Index(fields=['rating'], name='makazi_apar_rating_d4a323_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentreview',
            index=models.Index(fields=['is_approved'], name='makazi_apar_is_appr_fa7994_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentbooking',
            index=models.Index(fields=['status'], name='makazi_apar_status_64a631_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentbooking',
            index=models.Index(fields=['payment_status'], name='makazi_apar_payment_e5d949_idx'),
        ),
        migrations.AddIndex(
            model_name='apartmentbooking',
            index=models.Index(fields=['booking_date'], name='makazi_apar_booking_bcab2e_idx'),
        ),
    ]
