# Generated by Django 4.2.7 on 2025-12-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makazi', '0004_apartment_apartmentreview_apartmentbooking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='available_from',
        ),
    ]
