# Generated by Django 4.2.7 on 2025-12-30 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makazi', '0005_remove_apartment_available_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('address', models.TextField()),
                ('hostel_type', models.CharField(choices=[('university', 'University Hostel'), ('private', 'Private Hostel'), ('college', 'College Hostel'), ('veta', 'VETA Hostel'), ('polytechnic', 'Polytechnic Hostel')], max_length=50)),
                ('gender_allowed', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('warden_name', models.CharField(max_length=100)),
                ('warden_phone', models.CharField(max_length=20)),
                ('warden_email', models.EmailField(blank=True, max_length=254)),
                ('price_per_semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('caution_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('total_rooms', models.IntegerField(default=1)),
                ('available_rooms', models.IntegerField(default=1)),
                ('total_capacity', models.IntegerField(default=1)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('academic_year', models.CharField(default='2024/2025', max_length=20)),
                ('semester', models.CharField(choices=[('sem1', 'Semester 1'), ('sem2', 'Semester 2'), ('short', 'Short Course')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hostels/main/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='hostels/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='hostels/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_course', models.CharField(max_length=100)),
                ('student_year', models.CharField(max_length=20)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('security', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('facilities', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('management', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('would_recommend', models.BooleanField(default=True)),
                ('stay_duration', models.CharField(choices=[('semester', 'One Semester'), ('year', 'One Year'), ('multiple', 'Multiple Years'), ('short', 'Short Stay')], max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_verified_student', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='makazi.hostel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(help_text='University Registration Number', max_length=50)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=20)),
                ('student_course', models.CharField(max_length=100)),
                ('student_year', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('diploma', 'Diploma')], max_length=20)),
                ('booking_type', models.CharField(choices=[('semester', 'Full Semester'), ('monthly', 'Monthly'), ('short_term', 'Short Term'), ('academic_year', 'Full Academic Year')], max_length=20)),
                ('payment_option', models.CharField(choices=[('full_semester', 'Full Semester Payment'), ('monthly', 'Monthly Installments'), ('half_semester', 'Half Semester Payment')], default='full_semester', max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('duration_months', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_deadline', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('special_needs', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='makazi.hostel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['location'], name='makazi_host_locatio_ebf8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['university'], name='makazi_host_univers_12fe95_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['price_per_semester'], name='makazi_host_price_p_b48def_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_available'], name='makazi_host_is_avai_68c2eb_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['is_featured'], name='makazi_host_is_feat_364a76_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelreview',
            index=models.Index(fields=['hostel'], name='makazi_host_hostel__78d384_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelreview',
            index=models.Index(fields=['overall_rating'], name='makazi_host_overall_f90d69_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelreview',
            index=models.Index(fields=['is_approved'], name='makazi_host_is_appr_3e2e74_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelbooking',
            index=models.Index(fields=['status'], name='makazi_host_status_73b836_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelbooking',
            index=models.Index(fields=['payment_status'], name='makazi_host_payment_dcd36e_idx'),
        ),
        migrations.AddIndex(
            model_name='hostelbooking',
            index=models.Index(fields=['student_id'], name='makazi_host_student_25e0c8_idx'),
        ),
    ]
